#ifndef CLAUDE_DESKTOP_PROFILES_MANAGER_VERSION_H
#define CLAUDE_DESKTOP_PROFILES_MANAGER_VERSION_H

#define APP_VERSION_MAJOR 1
#define APP_VERSION_MINOR 1
#define APP_VERSION_PATCH 2
#define APP_VERSION_STR   "1.1.2"
#define APP_VERSION_WSTR  L"" APP_VERSION_STR

#endif
